### ISSUE TITLE
Tokenのmiddlewareの作成

### ISSUE THREAD

**Issue by take-cantik** [kyutech-programming-club/lt-hub-backend#5]
tokenがちゃんとしてなかったら弾くやつ

**Comment by syu-kwsk** [comment]
middlewareにどこまで仕事させるか分からんが、tokenの検証だけなら実装は後回しでもいい
とりあえず、すべてのリクエストは正しいトークンを持っていると仮定するってことで

middlewareで追加する関数は適当な（有効と判定されるはずの）uidを返すだけ
毎回デバッグ時に正しいトークンをつける必要がなくなる
